<template>
  <div class="wrap">
    <my-head :yaoluId="yaoluId" :showWork="false" :yaoluList="yaoluList" @newyaoluId="newyaoluId"></my-head>
    <div class="content">
      <div class="block">
        <p>请选择产品:</p>
        <ul class="goods clearfix">
          <li v-for="(item, index) in listGoods" :key="index" class="btn"
            :class="{bgcRed: index==currentGoods}" @click="goodsHandler(item,index)" >
            {{ item.model }}
          </li>
        </ul>
        <div v-for="(res,index) in pList[modelData.model]"
         :key="res.note" 
         style="display: flex"
         >
          <div class="tbText tb" @click="selectList3(res,index)" :class="{bgcRed:selProType.proCodeAll == res.proCodeAll}">{{res.specification+ '-' +res.proName}}</div>
        </div>

      </div>

      <div class="block">
        <p>请选择颜色：</p>
        <div class="colors">
          <div class="btn bgcGreen" v-for="(item, index) in listColor[currentGoods]" :key="index"
            :class="{bgcRed: index==currentColors}" @click="colorsHandler(index)" >
              {{ item.color_name }}
          </div>
        </div>
      </div>

      <div class="block">
        <p>请选择等级：</p>
        <div class="level">
          <div v-for="(item, index) in level" :key="index">
            <div class="btn bgcGreen" :class="{bgcRed1: item.showNum,bgcRed: index==currentLevel}" 
              @click="levelHandler(index)">
              {{ item.qlty_grade_name }}
            </div>
            <div class="num" v-show="item.showNum">
              <span class="sub" @click="sub(index)" onselectstart="return false">-</span>
              <input type="number" v-model.number="item.number" min="0">
              <span class="add" @click="add(index)" onselectstart="return false">+</span>
            </div>
          </div>
        </div>
      </div>

      <!-- <div class="block">
        <p @click="getTrade()">请选择商标：</p>
        <div class="trademark" v-for="(item, index) in trademark" :key="index">
          <div class="btn bgcGreen"
            :class="{bgcRed: index==currentTrademark}" @click="trademarkHandler(index)" >
             {{ item.clientFullName }}
          </div>
        </div>
      </div> -->

    </div>

    <div class="footBtn">
      <div v-show="showSubmit" class="save1" @click="submit(1)">保存并添加该工人</div>
      <div v-show="showSubmit" class="save2" @click="submit(2)">保存添加其他人</div>
      <div v-show="showSubmit" class="save2" @click="toAddQI">添加质量问题</div>
      <div class="goback" @click="$router.go(-1)">返回</div>
    </div>

    <toast v-model="showToast" @toastConfirm="toastConfirm"></toast>

    <msg v-model="showMsg" :msg="msg"></msg>

  </div>
</template>

<script>
import myHead from "@/components/my-head";
import toast from "@/components/toast";
import msg from "@/components/msg";
export default {
  name: "Goods",
  data() {
    return {
      title: "数据采集",
      //产品
      currentGoods: null,
      listGoods: [],
      //颜色
      listColor: [],
      modelIndex: 0,
      currentColors: 0,
      //商标
      currentTrademark:0,
      trademark:[],
      //等级
      currentLevel: null,
      level: [],
      showToast: false,
      showSubmit: false,
      showAddQ: false,
      submitType: null,
      worker: null,

      indexedDB: null,

      yaoluId: '',
      yaoluList:[],
      localData:[],

      showMsg: false,
      msg:'',
      nowTime: '',    //当前系统时间
      pList:{},
      modelData:'',
      productDataList:[],
      selectedProductList:[],
      selProType:'',
      selectedSpecification:''
    };
  },
  created() {
    this.getData();
    //this.getTrade();
  },
  computed:{
    baseURL(){
      return this.axios.defaults.baseURL
    },
    userCode(){
      return localStorage.getItem('userCode');
    }
  },
  methods: {
    newyaoluId(n){
      sessionStorage.setItem('yaoluId', n)
    },
    getNowFormatDate() {
      var date = new Date();
      var seperator1 = "-";
      var seperator2 = ":";
      var month = date.getMonth() + 1;
      var strDate = date.getDate();
      if (month >= 1 && month <= 9) {
          month = "0" + month;
      }
      if (strDate >= 0 && strDate <= 9) {
          strDate = "0" + strDate;
      }
      var currentdate = date.getFullYear() + seperator1 + month + seperator1 + strDate
              + " " + date.getHours() + seperator2 + date.getMinutes()
              + seperator2 + date.getSeconds();
      this.nowTime = date
    },        
    getData(){
      let that = this;
      const wList = {}
      const pList = {}
      let arrlist = []  
      localforage.getItem(that.baseURL + that.userCode).then(function(value) {
        if(sessionStorage.getItem('yaoluId')){
          that.yaoluId = sessionStorage.getItem('yaoluId');
        }else{
          that.yaoluId = value.ce_kiln[0].id+'';
        }
        that.yaoluList = value.ce_kiln;

        //获取本地数据
        that.indexedDB = value
        let query = location.href.myQueryUrlParameter();
        that.worker = query;

        //获取到当前员工下面的产品
        for(let i=0,len=value.ce_mold_asgmt.length; i<len; i++){
          if(value.ce_mold_asgmt[i].employee_no == query.employee_no){
            if(that.listGoods.length>0){
              let flag = that.listGoods.some(item=>{
                return item.model == value.ce_mold_asgmt[i].model
              })
              if(!flag){
                that.listGoods.push(value.ce_mold_asgmt[i]);
                that.listColor.push([]);
              }
            }else{
              that.listGoods.push(value.ce_mold_asgmt[i]);
              that.listColor.push([]);
            }
          }
        }
        
        that.compareArray(that.listGoods, 'model', true);
        
        //获取当前产品下面的颜色
        for(let i=0,len=that.listGoods.length; i<len; i++){
          for(let j=0,len=value.ce_material_model.length; j<len; j++){
            if(that.listGoods[i].model == value.ce_material_model[j].model){
              if(value.ce_material_model[j].colors){
                let colorArr = value.ce_material_model[j].colors.split(',');
                for(let z=0,len=colorArr.length; z<len; z++){
                  for(let k=0,len=value.ce_color.length; k<len; k++){
                    if (colorArr[z] == value.ce_color[k].id) {
                      that.listColor[i].push(value.ce_color[k])
                    }
                  }
                }
              }
            }
          }
        }
        for(let i=0,len=value.ce_quality_grade.length; i<len; i++){
          let obj = {
            number:0,
            showNum: false,
            ...value.ce_quality_grade[i]
          }
          that.level.push(obj)
        }
        for(let ele of value.ce_zhujiang_worker.modelList){
            if(!pList[ele.proCode]){
                pList[ele.proCode] = []
            }
            if(arrlist.indexOf(ele.proCode) < 0){
                arrlist.push(ele.proCode)
                for(let res of value.ce_zhujiang_worker.productList){  
                    if(ele.proCode == res.proCode){
                        pList[ele.proCode].push(res)                                         
                    }                              
                }                                
            }                                                            

        }
        that.wList = wList
        that.pList = pList           
      }).catch(function() {
          // 当出错时，此处代码运行
      });
    },
    getTrade(){
          let that = this;
      let url5 = '/mobile/selectClientTradeMark'
             this.axios.get(url5, {}).then(res => {// 成功回调
              if(res && res.status==200){
                let result = res.data.data
                this.trademark = result

              }
            }, () => {})
    },
    //===========排序start
    compareArray(arr, property, sequence) {
      for (var j = 0; j < arr.length - 1; j += 1) {
        // 两两比较，如果前一个比后一个大，则交换位置。
        for (var i = 0; i < arr.length - 1 - j; i += 1) {
          // 取出数组对应属性进行排序
          var before = this.compareString(arr[i][property], arr[i + 1][property]);
          if (before === 1) {
            var temp = arr[i];
            arr[i] = arr[i + 1];
            arr[i + 1] = temp;
          }
        }
      }
      if (sequence) {
        arr.reverse();
      }
      return arr;
    },
    compareString(str1, str2) {
        var str1Length = str1.length;
        var str2Length = str2.length;
        var StringLength = Math.min(str1Length, str2Length);
        var StringCode = '';
        var code = 0;
        // 字符串长度短的，排序靠前
        if (StringLength > 0) {
            for (var i = 0; i < StringLength; i += 1) {
                StringCode = this.compareCharacter(str1[i], str2[i]);
                if (StringCode === -1) {
                    code = -1;
                    break;
                } else if (StringCode === 1) {
                    code = 1;
                    break;
                } else {
                    code = 0;
                }
            }
            if (code === 0 && str1Length !== str2Length) {
                code = str1Length-str2Length <= -1 ? 1 : -1;
            }
        } else {// 对于空字符 串单独处理
            code = 0;
            if (code === 0 && str1Length !== str2Length) {
                code = str1Length-str2Length <= -1 ? 1 : -1;
            }
        }
        return code;
    },
    compareCharacter (Letter1, Letter2) {
        var Letter1TypeNum = this.DetermineType(Letter1);
        var Letter2TypeNum = this.DetermineType(Letter2);
        var before = '';
        var after = '';
        var code = '';
        // 不同类型排序
        if (Letter1TypeNum !== Letter2TypeNum) {
            code = Letter1TypeNum < Letter2TypeNum;
            return code? 1 : -1
        } else {
            // 同类型对比
            if (Letter1TypeNum === 0) {
                return code = 0;
            }

            if (Letter1TypeNum === 1) {
                before = Letter1;
                after = Letter2;
            }
            // 不区分大小写，依据英文字母Unicode码大小排序，a-z的Unicode码依次增加
            if (Letter1TypeNum === 2) {
                before = Letter1.toLocaleLowerCase().charCodeAt(0);
                after = Letter2.toLocaleLowerCase().charCodeAt(0);
            }
            if (Letter1TypeNum === 3) {
                // 转换成汉字对应拼音的首字母进行比较
                before = this.getFirstLetter(Letter1).toLocaleLowerCase().charCodeAt(0);
                after = this.getFirstLetter(Letter2).toLocaleLowerCase().charCodeAt(0);
            }
        }
        if (before > after) {
            code = -1;
        } else if (before === after) {
            code = 0;
        } else {
            code = 1;
        }

        return code;
    },
    DetermineType(Letter) {
        // 判断类型
        var isNum = !isNaN(Letter);
        var isLetter = /[_a-zA-Z]/.test(Letter);
        var isChinese = !/[^\u4E00-\u9FA5]/.test(Letter);
        var typeNum = '';
        if (isNum) {
            typeNum = 1;
        } else if (isLetter) {
            typeNum = 2;
        } else if (isChinese) {
            typeNum = 3;
        } else {
            typeNum = 0;
        }
        return typeNum;
    },
    getFirstLetter(str) {
      var pinyin_dict_firstletter = {};
      // 拼音首字母字典文件
      pinyin_dict_firstletter.all = "YDYQSXMWZSSXJBYMGCCZQPSSQBYCDSCDQLDYLYBSSJGYZZJJFKCCLZDHWDWZJLJPFYYNWJJTMYHZWZHFLZPPQHGSCYYYNJQYXXGJHHSDSJNKKTMOMLCRXYPSNQSECCQZGGLLYJLMYZZSECYKYYHQWJSSGGYXYZYJWWKDJHYCHMYXJTLXJYQBYXZLDWRDJRWYSRLDZJPCBZJJBRCFTLECZSTZFXXZHTRQHYBDLYCZSSYMMRFMYQZPWWJJYFCRWFDFZQPYDDWYXKYJAWJFFXYPSFTZYHHYZYSWCJYXSCLCXXWZZXNBGNNXBXLZSZSBSGPYSYZDHMDZBQBZCWDZZYYTZHBTSYYBZGNTNXQYWQSKBPHHLXGYBFMJEBJHHGQTJCYSXSTKZHLYCKGLYSMZXYALMELDCCXGZYRJXSDLTYZCQKCNNJWHJTZZCQLJSTSTBNXBTYXCEQXGKWJYFLZQLYHYXSPSFXLMPBYSXXXYDJCZYLLLSJXFHJXPJBTFFYABYXBHZZBJYZLWLCZGGBTSSMDTJZXPTHYQTGLJSCQFZKJZJQNLZWLSLHDZBWJNCJZYZSQQYCQYRZCJJWYBRTWPYFTWEXCSKDZCTBZHYZZYYJXZCFFZZMJYXXSDZZOTTBZLQWFCKSZSXFYRLNYJMBDTHJXSQQCCSBXYYTSYFBXDZTGBCNSLCYZZPSAZYZZSCJCSHZQYDXLBPJLLMQXTYDZXSQJTZPXLCGLQTZWJBHCTSYJSFXYEJJTLBGXSXJMYJQQPFZASYJNTYDJXKJCDJSZCBARTDCLYJQMWNQNCLLLKBYBZZSYHQQLTWLCCXTXLLZNTYLNEWYZYXCZXXGRKRMTCNDNJTSYYSSDQDGHSDBJGHRWRQLYBGLXHLGTGXBQJDZPYJSJYJCTMRNYMGRZJCZGJMZMGXMPRYXKJNYMSGMZJYMKMFXMLDTGFBHCJHKYLPFMDXLQJJSMTQGZSJLQDLDGJYCALCMZCSDJLLNXDJFFFFJCZFMZFFPFKHKGDPSXKTACJDHHZDDCRRCFQYJKQCCWJDXHWJLYLLZGCFCQDSMLZPBJJPLSBCJGGDCKKDEZSQCCKJGCGKDJTJDLZYCXKLQSCGJCLTFPCQCZGWPJDQYZJJBYJHSJDZWGFSJGZKQCCZLLPSPKJGQJHZZLJPLGJGJJTHJJYJZCZMLZLYQBGJWMLJKXZDZNJQSYZMLJLLJKYWXMKJLHSKJGBMCLYYMKXJQLBMLLKMDXXKWYXYSLMLPSJQQJQXYXFJTJDXMXXLLCXQBSYJBGWYMBGGBCYXPJYGPEPFGDJGBHBNSQJYZJKJKHXQFGQZKFHYGKHDKLLSDJQXPQYKYBNQSXQNSZSWHBSXWHXWBZZXDMNSJBSBKBBZKLYLXGWXDRWYQZMYWSJQLCJXXJXKJEQXSCYETLZHLYYYSDZPAQYZCMTLSHTZCFYZYXYLJSDCJQAGYSLCQLYYYSHMRQQKLDXZSCSSSYDYCJYSFSJBFRSSZQSBXXPXJYSDRCKGJLGDKZJZBDKTCSYQPYHSTCLDJDHMXMCGXYZHJDDTMHLTXZXYLYMOHYJCLTYFBQQXPFBDFHHTKSQHZYYWCNXXCRWHOWGYJLEGWDQCWGFJYCSNTMYTOLBYGWQWESJPWNMLRYDZSZTXYQPZGCWXHNGPYXSHMYQJXZTDPPBFYHZHTJYFDZWKGKZBLDNTSXHQEEGZZYLZMMZYJZGXZXKHKSTXNXXWYLYAPSTHXDWHZYMPXAGKYDXBHNHXKDPJNMYHYLPMGOCSLNZHKXXLPZZLBMLSFBHHGYGYYGGBHSCYAQTYWLXTZQCEZYDQDQMMHTKLLSZHLSJZWFYHQSWSCWLQAZYNYTLSXTHAZNKZZSZZLAXXZWWCTGQQTDDYZTCCHYQZFLXPSLZYGPZSZNGLNDQTBDLXGTCTAJDKYWNSYZLJHHZZCWNYYZYWMHYCHHYXHJKZWSXHZYXLYSKQYSPSLYZWMYPPKBYGLKZHTYXAXQSYSHXASMCHKDSCRSWJPWXSGZJLWWSCHSJHSQNHCSEGNDAQTBAALZZMSSTDQJCJKTSCJAXPLGGXHHGXXZCXPDMMHLDGTYBYSJMXHMRCPXXJZCKZXSHMLQXXTTHXWZFKHCCZDYTCJYXQHLXDHYPJQXYLSYYDZOZJNYXQEZYSQYAYXWYPDGXDDXSPPYZNDLTWRHXYDXZZJHTCXMCZLHPYYYYMHZLLHNXMYLLLMDCPPXHMXDKYCYRDLTXJCHHZZXZLCCLYLNZSHZJZZLNNRLWHYQSNJHXYNTTTKYJPYCHHYEGKCTTWLGQRLGGTGTYGYHPYHYLQYQGCWYQKPYYYTTTTLHYHLLTYTTSPLKYZXGZWGPYDSSZZDQXSKCQNMJJZZBXYQMJRTFFBTKHZKBXLJJKDXJTLBWFZPPTKQTZTGPDGNTPJYFALQMKGXBDCLZFHZCLLLLADPMXDJHLCCLGYHDZFGYDDGCYYFGYDXKSSEBDHYKDKDKHNAXXYBPBYYHXZQGAFFQYJXDMLJCSQZLLPCHBSXGJYNDYBYQSPZWJLZKSDDTACTBXZDYZYPJZQSJNKKTKNJDJGYYPGTLFYQKASDNTCYHBLWDZHBBYDWJRYGKZYHEYYFJMSDTYFZJJHGCXPLXHLDWXXJKYTCYKSSSMTWCTTQZLPBSZDZWZXGZAGYKTYWXLHLSPBCLLOQMMZSSLCMBJCSZZKYDCZJGQQDSMCYTZQQLWZQZXSSFPTTFQMDDZDSHDTDWFHTDYZJYQJQKYPBDJYYXTLJHDRQXXXHAYDHRJLKLYTWHLLRLLRCXYLBWSRSZZSYMKZZHHKYHXKSMDSYDYCJPBZBSQLFCXXXNXKXWYWSDZYQOGGQMMYHCDZTTFJYYBGSTTTYBYKJDHKYXBELHTYPJQNFXFDYKZHQKZBYJTZBXHFDXKDASWTAWAJLDYJSFHBLDNNTNQJTJNCHXFJSRFWHZFMDRYJYJWZPDJKZYJYMPCYZNYNXFBYTFYFWYGDBNZZZDNYTXZEMMQBSQEHXFZMBMFLZZSRXYMJGSXWZJSPRYDJSJGXHJJGLJJYNZZJXHGXKYMLPYYYCXYTWQZSWHWLYRJLPXSLSXMFSWWKLCTNXNYNPSJSZHDZEPTXMYYWXYYSYWLXJQZQXZDCLEEELMCPJPCLWBXSQHFWWTFFJTNQJHJQDXHWLBYZNFJLALKYYJLDXHHYCSTYYWNRJYXYWTRMDRQHWQCMFJDYZMHMYYXJWMYZQZXTLMRSPWWCHAQBXYGZYPXYYRRCLMPYMGKSJSZYSRMYJSNXTPLNBAPPYPYLXYYZKYNLDZYJZCZNNLMZHHARQMPGWQTZMXXMLLHGDZXYHXKYXYCJMFFYYHJFSBSSQLXXNDYCANNMTCJCYPRRNYTYQNYYMBMSXNDLYLYSLJRLXYSXQMLLYZLZJJJKYZZCSFBZXXMSTBJGNXYZHLXNMCWSCYZYFZLXBRNNNYLBNRTGZQYSATSWRYHYJZMZDHZGZDWYBSSCSKXSYHYTXXGCQGXZZSHYXJSCRHMKKBXCZJYJYMKQHZJFNBHMQHYSNJNZYBKNQMCLGQHWLZNZSWXKHLJHYYBQLBFCDSXDLDSPFZPSKJYZWZXZDDXJSMMEGJSCSSMGCLXXKYYYLNYPWWWGYDKZJGGGZGGSYCKNJWNJPCXBJJTQTJWDSSPJXZXNZXUMELPXFSXTLLXCLJXJJLJZXCTPSWXLYDHLYQRWHSYCSQYYBYAYWJJJQFWQCQQCJQGXALDBZZYJGKGXPLTZYFXJLTPADKYQHPMATLCPDCKBMTXYBHKLENXDLEEGQDYMSAWHZMLJTWYGXLYQZLJEEYYBQQFFNLYXRDSCTGJGXYYNKLLYQKCCTLHJLQMKKZGCYYGLLLJDZGYDHZWXPYSJBZKDZGYZZHYWYFQYTYZSZYEZZLYMHJJHTSMQWYZLKYYWZCSRKQYTLTDXWCTYJKLWSQZWBDCQYNCJSRSZJLKCDCDTLZZZACQQZZDDXYPLXZBQJYLZLLLQDDZQJYJYJZYXNYYYNYJXKXDAZWYRDLJYYYRJLXLLDYXJCYWYWNQCCLDDNYYYNYCKCZHXXCCLGZQJGKWPPCQQJYSBZZXYJSQPXJPZBSBDSFNSFPZXHDWZTDWPPTFLZZBZDMYYPQJRSDZSQZSQXBDGCPZSWDWCSQZGMDHZXMWWFYBPDGPHTMJTHZSMMBGZMBZJCFZWFZBBZMQCFMBDMCJXLGPNJBBXGYHYYJGPTZGZMQBQTCGYXJXLWZKYDPDYMGCFTPFXYZTZXDZXTGKMTYBBCLBJASKYTSSQYYMSZXFJEWLXLLSZBQJJJAKLYLXLYCCTSXMCWFKKKBSXLLLLJYXTYLTJYYTDPJHNHNNKBYQNFQYYZBYYESSESSGDYHFHWTCJBSDZZTFDMXHCNJZYMQWSRYJDZJQPDQBBSTJGGFBKJBXTGQHNGWJXJGDLLTHZHHYYYYYYSXWTYYYCCBDBPYPZYCCZYJPZYWCBDLFWZCWJDXXHYHLHWZZXJTCZLCDPXUJCZZZLYXJJTXPHFXWPYWXZPTDZZBDZCYHJHMLXBQXSBYLRDTGJRRCTTTHYTCZWMXFYTWWZCWJWXJYWCSKYBZSCCTZQNHXNWXXKHKFHTSWOCCJYBCMPZZYKBNNZPBZHHZDLSYDDYTYFJPXYNGFXBYQXCBHXCPSXTYZDMKYSNXSXLHKMZXLYHDHKWHXXSSKQYHHCJYXGLHZXCSNHEKDTGZXQYPKDHEXTYKCNYMYYYPKQYYYKXZLTHJQTBYQHXBMYHSQCKWWYLLHCYYLNNEQXQWMCFBDCCMLJGGXDQKTLXKGNQCDGZJWYJJLYHHQTTTNWCHMXCXWHWSZJYDJCCDBQCDGDNYXZTHCQRXCBHZTQCBXWGQWYYBXHMBYMYQTYEXMQKYAQYRGYZSLFYKKQHYSSQYSHJGJCNXKZYCXSBXYXHYYLSTYCXQTHYSMGSCPMMGCCCCCMTZTASMGQZJHKLOSQYLSWTMXSYQKDZLJQQYPLSYCZTCQQPBBQJZCLPKHQZYYXXDTDDTSJCXFFLLCHQXMJLWCJCXTSPYCXNDTJSHJWXDQQJSKXYAMYLSJHMLALYKXCYYDMNMDQMXMCZNNCYBZKKYFLMCHCMLHXRCJJHSYLNMTJZGZGYWJXSRXCWJGJQHQZDQJDCJJZKJKGDZQGJJYJYLXZXXCDQHHHEYTMHLFSBDJSYYSHFYSTCZQLPBDRFRZTZYKYWHSZYQKWDQZRKMSYNBCRXQBJYFAZPZZEDZCJYWBCJWHYJBQSZYWRYSZPTDKZPFPBNZTKLQYHBBZPNPPTYZZYBQNYDCPJMMCYCQMCYFZZDCMNLFPBPLNGQJTBTTNJZPZBBZNJKLJQYLNBZQHKSJZNGGQSZZKYXSHPZSNBCGZKDDZQANZHJKDRTLZLSWJLJZLYWTJNDJZJHXYAYNCBGTZCSSQMNJPJYTYSWXZFKWJQTKHTZPLBHSNJZSYZBWZZZZLSYLSBJHDWWQPSLMMFBJDWAQYZTCJTBNNWZXQXCDSLQGDSDPDZHJTQQPSWLYYJZLGYXYZLCTCBJTKTYCZJTQKBSJLGMGZDMCSGPYNJZYQYYKNXRPWSZXMTNCSZZYXYBYHYZAXYWQCJTLLCKJJTJHGDXDXYQYZZBYWDLWQCGLZGJGQRQZCZSSBCRPCSKYDZNXJSQGXSSJMYDNSTZTPBDLTKZWXQWQTZEXNQCZGWEZKSSBYBRTSSSLCCGBPSZQSZLCCGLLLZXHZQTHCZMQGYZQZNMCOCSZJMMZSQPJYGQLJYJPPLDXRGZYXCCSXHSHGTZNLZWZKJCXTCFCJXLBMQBCZZWPQDNHXLJCTHYZLGYLNLSZZPCXDSCQQHJQKSXZPBAJYEMSMJTZDXLCJYRYYNWJBNGZZTMJXLTBSLYRZPYLSSCNXPHLLHYLLQQZQLXYMRSYCXZLMMCZLTZSDWTJJLLNZGGQXPFSKYGYGHBFZPDKMWGHCXMSGDXJMCJZDYCABXJDLNBCDQYGSKYDQTXDJJYXMSZQAZDZFSLQXYJSJZYLBTXXWXQQZBJZUFBBLYLWDSLJHXJYZJWTDJCZFQZQZZDZSXZZQLZCDZFJHYSPYMPQZMLPPLFFXJJNZZYLSJEYQZFPFZKSYWJJJHRDJZZXTXXGLGHYDXCSKYSWMMZCWYBAZBJKSHFHJCXMHFQHYXXYZFTSJYZFXYXPZLCHMZMBXHZZSXYFYMNCWDABAZLXKTCSHHXKXJJZJSTHYGXSXYYHHHJWXKZXSSBZZWHHHCWTZZZPJXSNXQQJGZYZYWLLCWXZFXXYXYHXMKYYSWSQMNLNAYCYSPMJKHWCQHYLAJJMZXHMMCNZHBHXCLXTJPLTXYJHDYYLTTXFSZHYXXSJBJYAYRSMXYPLCKDUYHLXRLNLLSTYZYYQYGYHHSCCSMZCTZQXKYQFPYYRPFFLKQUNTSZLLZMWWTCQQYZWTLLMLMPWMBZSSTZRBPDDTLQJJBXZCSRZQQYGWCSXFWZLXCCRSZDZMCYGGDZQSGTJSWLJMYMMZYHFBJDGYXCCPSHXNZCSBSJYJGJMPPWAFFYFNXHYZXZYLREMZGZCYZSSZDLLJCSQFNXZKPTXZGXJJGFMYYYSNBTYLBNLHPFZDCYFBMGQRRSSSZXYSGTZRNYDZZCDGPJAFJFZKNZBLCZSZPSGCYCJSZLMLRSZBZZLDLSLLYSXSQZQLYXZLSKKBRXBRBZCYCXZZZEEYFGKLZLYYHGZSGZLFJHGTGWKRAAJYZKZQTSSHJJXDCYZUYJLZYRZDQQHGJZXSSZBYKJPBFRTJXLLFQWJHYLQTYMBLPZDXTZYGBDHZZRBGXHWNJTJXLKSCFSMWLSDQYSJTXKZSCFWJLBXFTZLLJZLLQBLSQMQQCGCZFPBPHZCZJLPYYGGDTGWDCFCZQYYYQYSSCLXZSKLZZZGFFCQNWGLHQYZJJCZLQZZYJPJZZBPDCCMHJGXDQDGDLZQMFGPSYTSDYFWWDJZJYSXYYCZCYHZWPBYKXRYLYBHKJKSFXTZJMMCKHLLTNYYMSYXYZPYJQYCSYCWMTJJKQYRHLLQXPSGTLYYCLJSCPXJYZFNMLRGJJTYZBXYZMSJYJHHFZQMSYXRSZCWTLRTQZSSTKXGQKGSPTGCZNJSJCQCXHMXGGZTQYDJKZDLBZSXJLHYQGGGTHQSZPYHJHHGYYGKGGCWJZZYLCZLXQSFTGZSLLLMLJSKCTBLLZZSZMMNYTPZSXQHJCJYQXYZXZQZCPSHKZZYSXCDFGMWQRLLQXRFZTLYSTCTMJCXJJXHJNXTNRZTZFQYHQGLLGCXSZSJDJLJCYDSJTLNYXHSZXCGJZYQPYLFHDJSBPCCZHJJJQZJQDYBSSLLCMYTTMQTBHJQNNYGKYRQYQMZGCJKPDCGMYZHQLLSLLCLMHOLZGDYYFZSLJCQZLYLZQJESHNYLLJXGJXLYSYYYXNBZLJSSZCQQCJYLLZLTJYLLZLLBNYLGQCHXYYXOXCXQKYJXXXYKLXSXXYQXCYKQXQCSGYXXYQXYGYTQOHXHXPYXXXULCYEYCHZZCBWQBBWJQZSCSZSSLZYLKDESJZWMYMCYTSDSXXSCJPQQSQYLYYZYCMDJDZYWCBTJSYDJKCYDDJLBDJJSODZYSYXQQYXDHHGQQYQHDYXWGMMMAJDYBBBPPBCMUUPLJZSMTXERXJMHQNUTPJDCBSSMSSSTKJTSSMMTRCPLZSZMLQDSDMJMQPNQDXCFYNBFSDQXYXHYAYKQYDDLQYYYSSZBYDSLNTFQTZQPZMCHDHCZCWFDXTMYQSPHQYYXSRGJCWTJTZZQMGWJJTJHTQJBBHWZPXXHYQFXXQYWYYHYSCDYDHHQMNMTMWCPBSZPPZZGLMZFOLLCFWHMMSJZTTDHZZYFFYTZZGZYSKYJXQYJZQBHMBZZLYGHGFMSHPZFZSNCLPBQSNJXZSLXXFPMTYJYGBXLLDLXPZJYZJYHHZCYWHJYLSJEXFSZZYWXKZJLUYDTMLYMQJPWXYHXSKTQJEZRPXXZHHMHWQPWQLYJJQJJZSZCPHJLCHHNXJLQWZJHBMZYXBDHHYPZLHLHLGFWLCHYYTLHJXCJMSCPXSTKPNHQXSRTYXXTESYJCTLSSLSTDLLLWWYHDHRJZSFGXTSYCZYNYHTDHWJSLHTZDQDJZXXQHGYLTZPHCSQFCLNJTCLZPFSTPDYNYLGMJLLYCQHYSSHCHYLHQYQTMZYPBYWRFQYKQSYSLZDQJMPXYYSSRHZJNYWTQDFZBWWTWWRXCWHGYHXMKMYYYQMSMZHNGCEPMLQQMTCWCTMMPXJPJJHFXYYZSXZHTYBMSTSYJTTQQQYYLHYNPYQZLCYZHZWSMYLKFJXLWGXYPJYTYSYXYMZCKTTWLKSMZSYLMPWLZWXWQZSSAQSYXYRHSSNTSRAPXCPWCMGDXHXZDZYFJHGZTTSBJHGYZSZYSMYCLLLXBTYXHBBZJKSSDMALXHYCFYGMQYPJYCQXJLLLJGSLZGQLYCJCCZOTYXMTMTTLLWTGPXYMZMKLPSZZZXHKQYSXCTYJZYHXSHYXZKXLZWPSQPYHJWPJPWXQQYLXSDHMRSLZZYZWTTCYXYSZZSHBSCCSTPLWSSCJCHNLCGCHSSPHYLHFHHXJSXYLLNYLSZDHZXYLSXLWZYKCLDYAXZCMDDYSPJTQJZLNWQPSSSWCTSTSZLBLNXSMNYYMJQBQHRZWTYYDCHQLXKPZWBGQYBKFCMZWPZLLYYLSZYDWHXPSBCMLJBSCGBHXLQHYRLJXYSWXWXZSLDFHLSLYNJLZYFLYJYCDRJLFSYZFSLLCQYQFGJYHYXZLYLMSTDJCYHBZLLNWLXXYGYYHSMGDHXXHHLZZJZXCZZZCYQZFNGWPYLCPKPYYPMCLQKDGXZGGWQBDXZZKZFBXXLZXJTPJPTTBYTSZZDWSLCHZHSLTYXHQLHYXXXYYZYSWTXZKHLXZXZPYHGCHKCFSYHUTJRLXFJXPTZTWHPLYXFCRHXSHXKYXXYHZQDXQWULHYHMJTBFLKHTXCWHJFWJCFPQRYQXCYYYQYGRPYWSGSUNGWCHKZDXYFLXXHJJBYZWTSXXNCYJJYMSWZJQRMHXZWFQSYLZJZGBHYNSLBGTTCSYBYXXWXYHXYYXNSQYXMQYWRGYQLXBBZLJSYLPSYTJZYHYZAWLRORJMKSCZJXXXYXCHDYXRYXXJDTSQFXLYLTSFFYXLMTYJMJUYYYXLTZCSXQZQHZXLYYXZHDNBRXXXJCTYHLBRLMBRLLAXKYLLLJLYXXLYCRYLCJTGJCMTLZLLCYZZPZPCYAWHJJFYBDYYZSMPCKZDQYQPBPCJPDCYZMDPBCYYDYCNNPLMTMLRMFMMGWYZBSJGYGSMZQQQZTXMKQWGXLLPJGZBQCDJJJFPKJKCXBLJMSWMDTQJXLDLPPBXCWRCQFBFQJCZAHZGMYKPHYYHZYKNDKZMBPJYXPXYHLFPNYYGXJDBKXNXHJMZJXSTRSTLDXSKZYSYBZXJLXYSLBZYSLHXJPFXPQNBYLLJQKYGZMCYZZYMCCSLCLHZFWFWYXZMWSXTYNXJHPYYMCYSPMHYSMYDYSHQYZCHMJJMZCAAGCFJBBHPLYZYLXXSDJGXDHKXXTXXNBHRMLYJSLTXMRHNLXQJXYZLLYSWQGDLBJHDCGJYQYCMHWFMJYBMBYJYJWYMDPWHXQLDYGPDFXXBCGJSPCKRSSYZJMSLBZZJFLJJJLGXZGYXYXLSZQYXBEXYXHGCXBPLDYHWETTWWCJMBTXCHXYQXLLXFLYXLLJLSSFWDPZSMYJCLMWYTCZPCHQEKCQBWLCQYDPLQPPQZQFJQDJHYMMCXTXDRMJWRHXCJZYLQXDYYNHYYHRSLSRSYWWZJYMTLTLLGTQCJZYABTCKZCJYCCQLJZQXALMZYHYWLWDXZXQDLLQSHGPJFJLJHJABCQZDJGTKHSSTCYJLPSWZLXZXRWGLDLZRLZXTGSLLLLZLYXXWGDZYGBDPHZPBRLWSXQBPFDWOFMWHLYPCBJCCLDMBZPBZZLCYQXLDOMZBLZWPDWYYGDSTTHCSQSCCRSSSYSLFYBFNTYJSZDFNDPDHDZZMBBLSLCMYFFGTJJQWFTMTPJWFNLBZCMMJTGBDZLQLPYFHYYMJYLSDCHDZJWJCCTLJCLDTLJJCPDDSQDSSZYBNDBJLGGJZXSXNLYCYBJXQYCBYLZCFZPPGKCXZDZFZTJJFJSJXZBNZYJQTTYJYHTYCZHYMDJXTTMPXSPLZCDWSLSHXYPZGTFMLCJTYCBPMGDKWYCYZCDSZZYHFLYCTYGWHKJYYLSJCXGYWJCBLLCSNDDBTZBSCLYZCZZSSQDLLMQYYHFSLQLLXFTYHABXGWNYWYYPLLSDLDLLBJCYXJZMLHLJDXYYQYTDLLLBUGBFDFBBQJZZMDPJHGCLGMJJPGAEHHBWCQXAXHHHZCHXYPHJAXHLPHJPGPZJQCQZGJJZZUZDMQYYBZZPHYHYBWHAZYJHYKFGDPFQSDLZMLJXKXGALXZDAGLMDGXMWZQYXXDXXPFDMMSSYMPFMDMMKXKSYZYSHDZKXSYSMMZZZMSYDNZZCZXFPLSTMZDNMXCKJMZTYYMZMZZMSXHHDCZJEMXXKLJSTLWLSQLYJZLLZJSSDPPMHNLZJCZYHMXXHGZCJMDHXTKGRMXFWMCGMWKDTKSXQMMMFZZYDKMSCLCMPCGMHSPXQPZDSSLCXKYXTWLWJYAHZJGZQMCSNXYYMMPMLKJXMHLMLQMXCTKZMJQYSZJSYSZHSYJZJCDAJZYBSDQJZGWZQQXFKDMSDJLFWEHKZQKJPEYPZYSZCDWYJFFMZZYLTTDZZEFMZLBNPPLPLPEPSZALLTYLKCKQZKGENQLWAGYXYDPXLHSXQQWQCQXQCLHYXXMLYCCWLYMQYSKGCHLCJNSZKPYZKCQZQLJPDMDZHLASXLBYDWQLWDNBQCRYDDZTJYBKBWSZDXDTNPJDTCTQDFXQQMGNXECLTTBKPWSLCTYQLPWYZZKLPYGZCQQPLLKCCYLPQMZCZQCLJSLQZDJXLDDHPZQDLJJXZQDXYZQKZLJCYQDYJPPYPQYKJYRMPCBYMCXKLLZLLFQPYLLLMBSGLCYSSLRSYSQTMXYXZQZFDZUYSYZTFFMZZSMZQHZSSCCMLYXWTPZGXZJGZGSJSGKDDHTQGGZLLBJDZLCBCHYXYZHZFYWXYZYMSDBZZYJGTSMTFXQYXQSTDGSLNXDLRYZZLRYYLXQHTXSRTZNGZXBNQQZFMYKMZJBZYMKBPNLYZPBLMCNQYZZZSJZHJCTZKHYZZJRDYZHNPXGLFZTLKGJTCTSSYLLGZRZBBQZZKLPKLCZYSSUYXBJFPNJZZXCDWXZYJXZZDJJKGGRSRJKMSMZJLSJYWQSKYHQJSXPJZZZLSNSHRNYPZTWCHKLPSRZLZXYJQXQKYSJYCZTLQZYBBYBWZPQDWWYZCYTJCJXCKCWDKKZXSGKDZXWWYYJQYYTCYTDLLXWKCZKKLCCLZCQQDZLQLCSFQCHQHSFSMQZZLNBJJZBSJHTSZDYSJQJPDLZCDCWJKJZZLPYCGMZWDJJBSJQZSYZYHHXJPBJYDSSXDZNCGLQMBTSFSBPDZDLZNFGFJGFSMPXJQLMBLGQCYYXBQKDJJQYRFKZTJDHCZKLBSDZCFJTPLLJGXHYXZCSSZZXSTJYGKGCKGYOQXJPLZPBPGTGYJZGHZQZZLBJLSQFZGKQQJZGYCZBZQTLDXRJXBSXXPZXHYZYCLWDXJJHXMFDZPFZHQHQMQGKSLYHTYCGFRZGNQXCLPDLBZCSCZQLLJBLHBZCYPZZPPDYMZZSGYHCKCPZJGSLJLNSCDSLDLXBMSTLDDFJMKDJDHZLZXLSZQPQPGJLLYBDSZGQLBZLSLKYYHZTTNTJYQTZZPSZQZTLLJTYYLLQLLQYZQLBDZLSLYYZYMDFSZSNHLXZNCZQZPBWSKRFBSYZMTHBLGJPMCZZLSTLXSHTCSYZLZBLFEQHLXFLCJLYLJQCBZLZJHHSSTBRMHXZHJZCLXFNBGXGTQJCZTMSFZKJMSSNXLJKBHSJXNTNLZDNTLMSJXGZJYJCZXYJYJWRWWQNZTNFJSZPZSHZJFYRDJSFSZJZBJFZQZZHZLXFYSBZQLZSGYFTZDCSZXZJBQMSZKJRHYJZCKMJKHCHGTXKXQGLXPXFXTRTYLXJXHDTSJXHJZJXZWZLCQSBTXWXGXTXXHXFTSDKFJHZYJFJXRZSDLLLTQSQQZQWZXSYQTWGWBZCGZLLYZBCLMQQTZHZXZXLJFRMYZFLXYSQXXJKXRMQDZDMMYYBSQBHGZMWFWXGMXLZPYYTGZYCCDXYZXYWGSYJYZNBHPZJSQSYXSXRTFYZGRHZTXSZZTHCBFCLSYXZLZQMZLMPLMXZJXSFLBYZMYQHXJSXRXSQZZZSSLYFRCZJRCRXHHZXQYDYHXSJJHZCXZBTYNSYSXJBQLPXZQPYMLXZKYXLXCJLCYSXXZZLXDLLLJJYHZXGYJWKJRWYHCPSGNRZLFZWFZZNSXGXFLZSXZZZBFCSYJDBRJKRDHHGXJLJJTGXJXXSTJTJXLYXQFCSGSWMSBCTLQZZWLZZKXJMLTMJYHSDDBXGZHDLBMYJFRZFSGCLYJBPMLYSMSXLSZJQQHJZFXGFQFQBPXZGYYQXGZTCQWYLTLGWSGWHRLFSFGZJMGMGBGTJFSYZZGZYZAFLSSPMLPFLCWBJZCLJJMZLPJJLYMQDMYYYFBGYGYZMLYZDXQYXRQQQHSYYYQXYLJTYXFSFSLLGNQCYHYCWFHCCCFXPYLYPLLZYXXXXXKQHHXSHJZCFZSCZJXCPZWHHHHHAPYLQALPQAFYHXDYLUKMZQGGGDDESRNNZLTZGCHYPPYSQJJHCLLJTOLNJPZLJLHYMHEYDYDSQYCDDHGZUNDZCLZYZLLZNTNYZGSLHSLPJJBDGWXPCDUTJCKLKCLWKLLCASSTKZZDNQNTTLYYZSSYSSZZRYLJQKCQDHHCRXRZYDGRGCWCGZQFFFPPJFZYNAKRGYWYQPQXXFKJTSZZXSWZDDFBBXTBGTZKZNPZZPZXZPJSZBMQHKCYXYLDKLJNYPKYGHGDZJXXEAHPNZKZTZCMXCXMMJXNKSZQNMNLWBWWXJKYHCPSTMCSQTZJYXTPCTPDTNNPGLLLZSJLSPBLPLQHDTNJNLYYRSZFFJFQWDPHZDWMRZCCLODAXNSSNYZRESTYJWJYJDBCFXNMWTTBYLWSTSZGYBLJPXGLBOCLHPCBJLTMXZLJYLZXCLTPNCLCKXTPZJSWCYXSFYSZDKNTLBYJCYJLLSTGQCBXRYZXBXKLYLHZLQZLNZCXWJZLJZJNCJHXMNZZGJZZXTZJXYCYYCXXJYYXJJXSSSJSTSSTTPPGQTCSXWZDCSYFPTFBFHFBBLZJCLZZDBXGCXLQPXKFZFLSYLTUWBMQJHSZBMDDBCYSCCLDXYCDDQLYJJWMQLLCSGLJJSYFPYYCCYLTJANTJJPWYCMMGQYYSXDXQMZHSZXPFTWWZQSWQRFKJLZJQQYFBRXJHHFWJJZYQAZMYFRHCYYBYQWLPEXCCZSTYRLTTDMQLYKMBBGMYYJPRKZNPBSXYXBHYZDJDNGHPMFSGMWFZMFQMMBCMZZCJJLCNUXYQLMLRYGQZCYXZLWJGCJCGGMCJNFYZZJHYCPRRCMTZQZXHFQGTJXCCJEAQCRJYHPLQLSZDJRBCQHQDYRHYLYXJSYMHZYDWLDFRYHBPYDTSSCNWBXGLPZMLZZTQSSCPJMXXYCSJYTYCGHYCJWYRXXLFEMWJNMKLLSWTXHYYYNCMMCWJDQDJZGLLJWJRKHPZGGFLCCSCZMCBLTBHBQJXQDSPDJZZGKGLFQYWBZYZJLTSTDHQHCTCBCHFLQMPWDSHYYTQWCNZZJTLBYMBPDYYYXSQKXWYYFLXXNCWCXYPMAELYKKJMZZZBRXYYQJFLJPFHHHYTZZXSGQQMHSPGDZQWBWPJHZJDYSCQWZKTXXSQLZYYMYSDZGRXCKKUJLWPYSYSCSYZLRMLQSYLJXBCXTLWDQZPCYCYKPPPNSXFYZJJRCEMHSZMSXLXGLRWGCSTLRSXBZGBZGZTCPLUJLSLYLYMTXMTZPALZXPXJTJWTCYYZLBLXBZLQMYLXPGHDSLSSDMXMBDZZSXWHAMLCZCPJMCNHJYSNSYGCHSKQMZZQDLLKABLWJXSFMOCDXJRRLYQZKJMYBYQLYHETFJZFRFKSRYXFJTWDSXXSYSQJYSLYXWJHSNLXYYXHBHAWHHJZXWMYLJCSSLKYDZTXBZSYFDXGXZJKHSXXYBSSXDPYNZWRPTQZCZENYGCXQFJYKJBZMLJCMQQXUOXSLYXXLYLLJDZBTYMHPFSTTQQWLHOKYBLZZALZXQLHZWRRQHLSTMYPYXJJXMQSJFNBXYXYJXXYQYLTHYLQYFMLKLJTMLLHSZWKZHLJMLHLJKLJSTLQXYLMBHHLNLZXQJHXCFXXLHYHJJGBYZZKBXSCQDJQDSUJZYYHZHHMGSXCSYMXFEBCQWWRBPYYJQTYZCYQYQQZYHMWFFHGZFRJFCDPXNTQYZPDYKHJLFRZXPPXZDBBGZQSTLGDGYLCQMLCHHMFYWLZYXKJLYPQHSYWMQQGQZMLZJNSQXJQSYJYCBEHSXFSZPXZWFLLBCYYJDYTDTHWZSFJMQQYJLMQXXLLDTTKHHYBFPWTYYSQQWNQWLGWDEBZWCMYGCULKJXTMXMYJSXHYBRWFYMWFRXYQMXYSZTZZTFYKMLDHQDXWYYNLCRYJBLPSXCXYWLSPRRJWXHQYPHTYDNXHHMMYWYTZCSQMTSSCCDALWZTCPQPYJLLQZYJSWXMZZMMYLMXCLMXCZMXMZSQTZPPQQBLPGXQZHFLJJHYTJSRXWZXSCCDLXTYJDCQJXSLQYCLZXLZZXMXQRJMHRHZJBHMFLJLMLCLQNLDXZLLLPYPSYJYSXCQQDCMQJZZXHNPNXZMEKMXHYKYQLXSXTXJYYHWDCWDZHQYYBGYBCYSCFGPSJNZDYZZJZXRZRQJJYMCANYRJTLDPPYZBSTJKXXZYPFDWFGZZRPYMTNGXZQBYXNBUFNQKRJQZMJEGRZGYCLKXZDSKKNSXKCLJSPJYYZLQQJYBZSSQLLLKJXTBKTYLCCDDBLSPPFYLGYDTZJYQGGKQTTFZXBDKTYYHYBBFYTYYBCLPDYTGDHRYRNJSPTCSNYJQHKLLLZSLYDXXWBCJQSPXBPJZJCJDZFFXXBRMLAZHCSNDLBJDSZBLPRZTSWSBXBCLLXXLZDJZSJPYLYXXYFTFFFBHJJXGBYXJPMMMPSSJZJMTLYZJXSWXTYLEDQPJMYGQZJGDJLQJWJQLLSJGJGYGMSCLJJXDTYGJQJQJCJZCJGDZZSXQGSJGGCXHQXSNQLZZBXHSGZXCXYLJXYXYYDFQQJHJFXDHCTXJYRXYSQTJXYEFYYSSYYJXNCYZXFXMSYSZXYYSCHSHXZZZGZZZGFJDLTYLNPZGYJYZYYQZPBXQBDZTZCZYXXYHHSQXSHDHGQHJHGYWSZTMZMLHYXGEBTYLZKQWYTJZRCLEKYSTDBCYKQQSAYXCJXWWGSBHJYZYDHCSJKQCXSWXFLTYNYZPZCCZJQTZWJQDZZZQZLJJXLSBHPYXXPSXSHHEZTXFPTLQYZZXHYTXNCFZYYHXGNXMYWXTZSJPTHHGYMXMXQZXTSBCZYJYXXTYYZYPCQLMMSZMJZZLLZXGXZAAJZYXJMZXWDXZSXZDZXLEYJJZQBHZWZZZQTZPSXZTDSXJJJZNYAZPHXYYSRNQDTHZHYYKYJHDZXZLSWCLYBZYECWCYCRYLCXNHZYDZYDYJDFRJJHTRSQTXYXJRJHOJYNXELXSFSFJZGHPZSXZSZDZCQZBYYKLSGSJHCZSHDGQGXYZGXCHXZJWYQWGYHKSSEQZZNDZFKWYSSTCLZSTSYMCDHJXXYWEYXCZAYDMPXMDSXYBSQMJMZJMTZQLPJYQZCGQHXJHHLXXHLHDLDJQCLDWBSXFZZYYSCHTYTYYBHECXHYKGJPXHHYZJFXHWHBDZFYZBCAPNPGNYDMSXHMMMMAMYNBYJTMPXYYMCTHJBZYFCGTYHWPHFTWZZEZSBZEGPFMTSKFTYCMHFLLHGPZJXZJGZJYXZSBBQSCZZLZCCSTPGXMJSFTCCZJZDJXCYBZLFCJSYZFGSZLYBCWZZBYZDZYPSWYJZXZBDSYUXLZZBZFYGCZXBZHZFTPBGZGEJBSTGKDMFHYZZJHZLLZZGJQZLSFDJSSCBZGPDLFZFZSZYZYZSYGCXSNXXCHCZXTZZLJFZGQSQYXZJQDCCZTQCDXZJYQJQCHXZTDLGSCXZSYQJQTZWLQDQZTQCHQQJZYEZZZPBWKDJFCJPZTYPQYQTTYNLMBDKTJZPQZQZZFPZSBNJLGYJDXJDZZKZGQKXDLPZJTCJDQBXDJQJSTCKNXBXZMSLYJCQMTJQWWCJQNJNLLLHJCWQTBZQYDZCZPZZDZYDDCYZZZCCJTTJFZDPRRTZTJDCQTQZDTJNPLZBCLLCTZSXKJZQZPZLBZRBTJDCXFCZDBCCJJLTQQPLDCGZDBBZJCQDCJWYNLLZYZCCDWLLXWZLXRXNTQQCZXKQLSGDFQTDDGLRLAJJTKUYMKQLLTZYTDYYCZGJWYXDXFRSKSTQTENQMRKQZHHQKDLDAZFKYPBGGPZREBZZYKZZSPEGJXGYKQZZZSLYSYYYZWFQZYLZZLZHWCHKYPQGNPGBLPLRRJYXCCSYYHSFZFYBZYYTGZXYLXCZWXXZJZBLFFLGSKHYJZEYJHLPLLLLCZGXDRZELRHGKLZZYHZLYQSZZJZQLJZFLNBHGWLCZCFJYSPYXZLZLXGCCPZBLLCYBBBBUBBCBPCRNNZCZYRBFSRLDCGQYYQXYGMQZWTZYTYJXYFWTEHZZJYWLCCNTZYJJZDEDPZDZTSYQJHDYMBJNYJZLXTSSTPHNDJXXBYXQTZQDDTJTDYYTGWSCSZQFLSHLGLBCZPHDLYZJYCKWTYTYLBNYTSDSYCCTYSZYYEBHEXHQDTWNYGYCLXTSZYSTQMYGZAZCCSZZDSLZCLZRQXYYELJSBYMXSXZTEMBBLLYYLLYTDQYSHYMRQWKFKBFXNXSBYCHXBWJYHTQBPBSBWDZYLKGZSKYHXQZJXHXJXGNLJKZLYYCDXLFYFGHLJGJYBXQLYBXQPQGZTZPLNCYPXDJYQYDYMRBESJYYHKXXSTMXRCZZYWXYQYBMCLLYZHQYZWQXDBXBZWZMSLPDMYSKFMZKLZCYQYCZLQXFZZYDQZPZYGYJYZMZXDZFYFYTTQTZHGSPCZMLCCYTZXJCYTJMKSLPZHYSNZLLYTPZCTZZCKTXDHXXTQCYFKSMQCCYYAZHTJPCYLZLYJBJXTPNYLJYYNRXSYLMMNXJSMYBCSYSYLZYLXJJQYLDZLPQBFZZBLFNDXQKCZFYWHGQMRDSXYCYTXNQQJZYYPFZXDYZFPRXEJDGYQBXRCNFYYQPGHYJDYZXGRHTKYLNWDZNTSMPKLBTHBPYSZBZTJZSZZJTYYXZPHSSZZBZCZPTQFZMYFLYPYBBJQXZMXXDJMTSYSKKBJZXHJCKLPSMKYJZCXTMLJYXRZZQSLXXQPYZXMKYXXXJCLJPRMYYGADYSKQLSNDHYZKQXZYZTCGHZTLMLWZYBWSYCTBHJHJFCWZTXWYTKZLXQSHLYJZJXTMPLPYCGLTBZZTLZJCYJGDTCLKLPLLQPJMZPAPXYZLKKTKDZCZZBNZDYDYQZJYJGMCTXLTGXSZLMLHBGLKFWNWZHDXUHLFMKYSLGXDTWWFRJEJZTZHYDXYKSHWFZCQSHKTMQQHTZHYMJDJSKHXZJZBZZXYMPAGQMSTPXLSKLZYNWRTSQLSZBPSPSGZWYHTLKSSSWHZZLYYTNXJGMJSZSUFWNLSOZTXGXLSAMMLBWLDSZYLAKQCQCTMYCFJBSLXCLZZCLXXKSBZQCLHJPSQPLSXXCKSLNHPSFQQYTXYJZLQLDXZQJZDYYDJNZPTUZDSKJFSLJHYLZSQZLBTXYDGTQFDBYAZXDZHZJNHHQBYKNXJJQCZMLLJZKSPLDYCLBBLXKLELXJLBQYCXJXGCNLCQPLZLZYJTZLJGYZDZPLTQCSXFDMNYCXGBTJDCZNBGBQYQJWGKFHTNPYQZQGBKPBBYZMTJDYTBLSQMPSXTBNPDXKLEMYYCJYNZCTLDYKZZXDDXHQSHDGMZSJYCCTAYRZLPYLTLKXSLZCGGEXCLFXLKJRTLQJAQZNCMBYDKKCXGLCZJZXJHPTDJJMZQYKQSECQZDSHHADMLZFMMZBGNTJNNLGBYJBRBTMLBYJDZXLCJLPLDLPCQDHLXZLYCBLCXZZJADJLNZMMSSSMYBHBSQKBHRSXXJMXSDZNZPXLGBRHWGGFCXGMSKLLTSJYYCQLTSKYWYYHYWXBXQYWPYWYKQLSQPTNTKHQCWDQKTWPXXHCPTHTWUMSSYHBWCRWXHJMKMZNGWTMLKFGHKJYLSYYCXWHYECLQHKQHTTQKHFZLDXQWYZYYDESBPKYRZPJFYYZJCEQDZZDLATZBBFJLLCXDLMJSSXEGYGSJQXCWBXSSZPDYZCXDNYXPPZYDLYJCZPLTXLSXYZYRXCYYYDYLWWNZSAHJSYQYHGYWWAXTJZDAXYSRLTDPSSYYFNEJDXYZHLXLLLZQZSJNYQYQQXYJGHZGZCYJCHZLYCDSHWSHJZYJXCLLNXZJJYYXNFXMWFPYLCYLLABWDDHWDXJMCXZTZPMLQZHSFHZYNZTLLDYWLSLXHYMMYLMBWWKYXYADTXYLLDJPYBPWUXJMWMLLSAFDLLYFLBHHHBQQLTZJCQJLDJTFFKMMMBYTHYGDCQRDDWRQJXNBYSNWZDBYYTBJHPYBYTTJXAAHGQDQTMYSTQXKBTZPKJLZRBEQQSSMJJBDJOTGTBXPGBKTLHQXJJJCTHXQDWJLWRFWQGWSHCKRYSWGFTGYGBXSDWDWRFHWYTJJXXXJYZYSLPYYYPAYXHYDQKXSHXYXGSKQHYWFDDDPPLCJLQQEEWXKSYYKDYPLTJTHKJLTCYYHHJTTPLTZZCDLTHQKZXQYSTEEYWYYZYXXYYSTTJKLLPZMCYHQGXYHSRMBXPLLNQYDQHXSXXWGDQBSHYLLPJJJTHYJKYPPTHYYKTYEZYENMDSHLCRPQFDGFXZPSFTLJXXJBSWYYSKSFLXLPPLBBBLBSFXFYZBSJSSYLPBBFFFFSSCJDSTZSXZRYYSYFFSYZYZBJTBCTSBSDHRTJJBYTCXYJEYLXCBNEBJDSYXYKGSJZBXBYTFZWGENYHHTHZHHXFWGCSTBGXKLSXYWMTMBYXJSTZSCDYQRCYTWXZFHMYMCXLZNSDJTTTXRYCFYJSBSDYERXJLJXBBDEYNJGHXGCKGSCYMBLXJMSZNSKGXFBNBPTHFJAAFXYXFPXMYPQDTZCXZZPXRSYWZDLYBBKTYQPQJPZYPZJZNJPZJLZZFYSBTTSLMPTZRTDXQSJEHBZYLZDHLJSQMLHTXTJECXSLZZSPKTLZKQQYFSYGYWPCPQFHQHYTQXZKRSGTTSQCZLPTXCDYYZXSQZSLXLZMYCPCQBZYXHBSXLZDLTCDXTYLZJYYZPZYZLTXJSJXHLPMYTXCQRBLZSSFJZZTNJYTXMYJHLHPPLCYXQJQQKZZSCPZKSWALQSBLCCZJSXGWWWYGYKTJBBZTDKHXHKGTGPBKQYSLPXPJCKBMLLXDZSTBKLGGQKQLSBKKTFXRMDKBFTPZFRTBBRFERQGXYJPZSSTLBZTPSZQZSJDHLJQLZBPMSMMSXLQQNHKNBLRDDNXXDHDDJCYYGYLXGZLXSYGMQQGKHBPMXYXLYTQWLWGCPBMQXCYZYDRJBHTDJYHQSHTMJSBYPLWHLZFFNYPMHXXHPLTBQPFBJWQDBYGPNZTPFZJGSDDTQSHZEAWZZYLLTYYBWJKXXGHLFKXDJTMSZSQYNZGGSWQSPHTLSSKMCLZXYSZQZXNCJDQGZDLFNYKLJCJLLZLMZZNHYDSSHTHZZLZZBBHQZWWYCRZHLYQQJBEYFXXXWHSRXWQHWPSLMSSKZTTYGYQQWRSLALHMJTQJSMXQBJJZJXZYZKXBYQXBJXSHZTSFJLXMXZXFGHKZSZGGYLCLSARJYHSLLLMZXELGLXYDJYTLFBHBPNLYZFBBHPTGJKWETZHKJJXZXXGLLJLSTGSHJJYQLQZFKCGNNDJSSZFDBCTWWSEQFHQJBSAQTGYPQLBXBMMYWXGSLZHGLZGQYFLZBYFZJFRYSFMBYZHQGFWZSYFYJJPHZBYYZFFWODGRLMFTWLBZGYCQXCDJYGZYYYYTYTYDWEGAZYHXJLZYYHLRMGRXXZCLHNELJJTJTPWJYBJJBXJJTJTEEKHWSLJPLPSFYZPQQBDLQJJTYYQLYZKDKSQJYYQZLDQTGJQYZJSUCMRYQTHTEJMFCTYHYPKMHYZWJDQFHYYXWSHCTXRLJHQXHCCYYYJLTKTTYTMXGTCJTZAYYOCZLYLBSZYWJYTSJYHBYSHFJLYGJXXTMZYYLTXXYPZLXYJZYZYYPNHMYMDYYLBLHLSYYQQLLNJJYMSOYQBZGDLYXYLCQYXTSZEGXHZGLHWBLJHEYXTWQMAKBPQCGYSHHEGQCMWYYWLJYJHYYZLLJJYLHZYHMGSLJLJXCJJYCLYCJPCPZJZJMMYLCQLNQLJQJSXYJMLSZLJQLYCMMHCFMMFPQQMFYLQMCFFQMMMMHMZNFHHJGTTHHKHSLNCHHYQDXTMMQDCYZYXYQMYQYLTDCYYYZAZZCYMZYDLZFFFMMYCQZWZZMABTBYZTDMNZZGGDFTYPCGQYTTSSFFWFDTZQSSYSTWXJHXYTSXXYLBYQHWWKXHZXWZNNZZJZJJQJCCCHYYXBZXZCYZTLLCQXYNJYCYYCYNZZQYYYEWYCZDCJYCCHYJLBTZYYCQWMPWPYMLGKDLDLGKQQBGYCHJXY";
      var dict = {};
      if (!str || /^ +$/g.test(str)) return '';
      dict.firstletter = pinyin_dict_firstletter;
      if (dict.firstletter) {// 使用首字母字典文件
          var result = [];
          for (var i = 0; i < str.length; i++) {
              var unicode = str.charCodeAt(i);
              var ch = str.charAt(i);
              if (unicode >= 19968 && unicode <= 40869) {
                  ch = dict.firstletter.all.charAt(unicode - 19968);
              }
              result.push(ch);
          }
          return result.join('');
      }
    },
    //==============排序end
    goodsHandler(item,index) {
      let that = this
      this.modelData = item
      this.currentGoods = index;
      this.modelIndex = index
      this.selectedProductList = that.pList[item.model]
    },
    selectList3(res,index){
      this.selProType = res
      this.selectedSpecification = res.specification
    },
    colorsHandler(index) {
      this.currentColors = index;
    },
    levelHandler(index) {
      this.showSubmit = true;
      if(index != 0) this.showAddQ = true;
      this.currentLevel = index;
      this.level.map(item=>{
        if(item.number>0) {
          item.showNum = true
        } else{
          item.showNum = false
        }
      })
      this.level[index].showNum = true
      if(this.level[index].number == 0){
        this.level[index].number = 1
      }
    },
    trademarkHandler(index) {
      this.currentTrademark = index;
    },
    //加
    add(i) {
      this.level[i].number += 1
      this.level.map((item,index)=>{
        if(index!=0 && item.number>0) this.showAddQ = true;
        if(item.number>0) {
          this.showSubmit = true;
          item.showNum = true
        }
      })
    },
    //减
    sub(i) {
      if (this.level[i].number == 0) return;
      this.level[i].number -= 1;

      let n1 = this.level.every(item=>{
        return item.number==0
      })
      if(n1) this.showSubmit = false;

      let n2 = this.level.slice(1).every(item => {
        return item.number==0
      })
      if(n2) this.showAddQ = false;
    },
    submit(n) {
      this.getNowFormatDate()
      this.showToast = true;
      this.submitType = n;
    },
    //弹窗确定回调方法
    toastConfirm(n) {
      let that = this;
      let pro = that.listGoods[that.currentGoods]
      let number = 0, grade_id='', grade_name='', grade_number='', problem_style, problem_style_col; 
      let problem_id='', problem_name='', problem_number='', problemEmployeeId='', problemEmployeeName='',productAll='';

      that.level.map(item=>{
        number += item.number*1;
        grade_id += item.id + ',';
        grade_name += item.qlty_grade_name + ',';
        if(item.number != 0){
          grade_number += item.number + ','
        } else {
          grade_number += ','
        }
      })
      
      let gongzhongId=[],gongzhongName=[];
      //所有工种name 并将‘成型工’排在第一
      for(let i=0, len=that.indexedDB.ce_quality_issue.length; i<len; i++){
        if(gongzhongName.indexOf(that.indexedDB.ce_quality_issue[i].resp_pos_id) < 0){
          gongzhongName.push(that.indexedDB.ce_quality_issue[i].resp_pos_id)
        }
      }
      if(gongzhongName[0] != '成型工'){
        let index=null;
        for(let i=0; i<gongzhongName.length; i++){
          if(gongzhongName[i] == '成型工'){
            index = i;
          }
        }
        let str = gongzhongName.splice(index, 1);
        gongzhongName.unshift(str[0])
      }
      //所有工种id
      for(let i=0,len=gongzhongName.length; i<len; i++){
        for(let j=0,len=that.indexedDB.t_partner_role_def.length; j<len; j++){
          if(gongzhongName[i] == that.indexedDB.t_partner_role_def[j].name){
            gongzhongId.push(that.indexedDB.t_partner_role_def[j].id)
          }
        }
        //所有问题id name //采集的问题数量
        for(let k=0,len=that.indexedDB.ce_quality_issue.length; k<len; k++){
          if(gongzhongName[i] == that.indexedDB.ce_quality_issue[k].resp_pos_id){
            problem_name += that.indexedDB.ce_quality_issue[k].issue_name + ',';
            problem_id += that.indexedDB.ce_quality_issue[k].id + ',';
            problem_number += ','
          }
        }
      }

      let listWorker = [];//工种
      let listGroup = [];//分组
      let listQuestion = [];//问题
      //根据工种名字获取 工种的id和  设置list的数据结构
      for(let i=0,len=gongzhongName.length; i<len; i++){
        for(let j=0,len=that.indexedDB.t_partner_role_def.length; j<len; j++){
          if(gongzhongName[i] == that.indexedDB.t_partner_role_def[j].name){
            gongzhongId.push(that.indexedDB.t_partner_role_def[j].id)
            listWorker.push({
              gongzhongId: that.indexedDB.t_partner_role_def[j].id,
              gongzhongName: gongzhongName[i],
              isCheckedNum: false,//是否添加过问题类型 （number大于零）
            })
            listGroup.push([]);
            listQuestion.push([]);
          }
        }
      }
      //问题
      for(let i=0,len=listWorker.length; i<len; i++){
        for(let k=0,len=that.indexedDB.t_contact.length; k<len; k++){
          if(listWorker[i].gongzhongName == that.indexedDB.t_contact[k].job_pos_name){
            listGroup[i].push(that.indexedDB.t_contact[k])
          }
        }

        for(let j=0, len=that.indexedDB.ce_quality_issue.length; j<len; j++){
          if(listWorker[i].gongzhongName == that.indexedDB.ce_quality_issue[j].resp_pos_id){
            let obj = {number:0, ...that.indexedDB.ce_quality_issue[j]}
            listQuestion[i].push(obj)
          }
        }
      }
      
      if(that.showAddQ){
        for(let i=0,len=listGroup.length; i<len; i++){
          for(let j=0,len=listGroup[i].length; j<len; j++){
            problemEmployeeId += listGroup[i][j].partner_id + ','
            problemEmployeeName += listGroup[i][j].name + ','
          }
        }
      }else{
        problemEmployeeId = ',,,,,';
        problemEmployeeName = ',,,,,'
      }
      let problemStyleCol = []
      listQuestion.map(item=>{
        problemStyleCol.push(item.length + 1);
      })
      let kiln_name;
      that.yaoluList.map(item => {
        if(item.id == sessionStorage.getItem('yaoluId')){
          kiln_name = item.kiln_name
        }
      })
      let color_name = '';
      if(that.listColor.length>0 && that.listColor[that.currentGoods] && that.listColor[that.currentGoods][that.currentColors]){
        color_name = that.listColor[that.currentGoods][that.currentColors].color_name;
      }
      let trademark='';
      if(this.trademark[this.currentTrademark]){
            trademark = this.trademark[this.currentTrademark].clientFullName;
      }else{
      trademark=null;
      }

       if(pro==undefined){
            alert("请选择产品型号");
            return;
       }

      if(that.selectedSpecification == ''){
          productAll = pro.model
      }
      if(that.selectedSpecification != ''){
          productAll = pro.model +'#'+ that.selectedSpecification
      }   

      let param = {
        proCode: productAll,//产品型号
        workerCode: that.worker.employee_no,//工号
        workerName: that.worker.name,//
        color: color_name,//颜色，传字符串
        workspace: null,//成型车间
        number: number,//送检总数
        gradeId: grade_id.substring(0, grade_id.length-1),//等级id
        gradeName: grade_name.substring(0, grade_name.length-1),//等级name
        gradeNumber: grade_number.substring(0, grade_number.length-1),//采集的各等级的数量

        problemStyle: gongzhongName.toString(),//所有工种name
        problemStyleCol: problemStyleCol.toString(),//各工种下面有多少种问题
        problemId: problem_id.substring(0, problem_id.length-1),//所有问题id
        problemName: problem_name.substring(0, problem_name.length-1),//所有问题name
        problemNumber: problem_number.substring(0, problem_number.length-1),//采集的问题数量
        problemEmployeeId: ',,,,,',//组长id
        problemEmployeeName: ',,,,,',//组长name
        kilnName: kiln_name,
        trademark:trademark,    //商标
        time: new Date(sessionStorage.getItem('dateCJ')),
        createTime: that.nowTime,   //点击保存的时间
      }


      let data = [param]
      console.log(param);

      let url = '/Collection/insertIpadData';
      that.axios.post(url, data).then(res => {// 成功回调
        if(res && res.status==200){
          that.msg = '保存成功';
          that.showMsg = true;
          setTimeout(()=>{
            that.showMsg = false;
            if (that.submitType == 2) {
              //保存并添加其他工人
              window.history.back(-1)
            } else {
              //window.location.reload();
              that.currentGoods = 0;
              that.currentColors = 0;
              that.currentLevel = null;
              that.selProType = ''
              that.level.map(nn => {
                nn.showNum = false;
                nn.number = 0;
              })
            }
          },1000)
          that.showToast = n;
        }
      }, res => {
        that.showToast = false;
        localforage.getItem('local' + that.baseURL + that.userCode).then(function(value) {
          let res = JSON.parse(value)
          if(!res){
            let arr = []
            arr.push(param)
            localforage.setItem('local' + that.baseURL + that.userCode, JSON.stringify(arr)).then(function (){
                // 当值被存储后，可执行其他操作
            }).catch(function(err) {
                // 当出错时，此处代码运行
            });
          }else{
            that.localData = JSON.parse(value).concat();
            that.localData.push(param)
            localforage.removeItem('local' + that.baseURL + that.userCode).then(function() {
              localforage.setItem('local' + that.baseURL + that.userCode, JSON.stringify(that.localData)).then(function () {
                // 当值被存储后，可执行其他操作
              }).catch(function(err) {
                  // 当出错时，此处代码运行
              });
            }).catch(function() {

            });
          }
        }).catch(function() {
            // 当出错时，此处代码运行
        });
        that.msg = '当前无网络，数据已保存本地';
        that.showMsg = true;
        setTimeout(()=>{
          that.showMsg = false;
          if (that.submitType == 2) {
            //保存并添加其他工人
            window.history.back(-1);
          } else {
            //保存并继续添加当前工人
            that.currentGoods = 0;
            that.currentColors = 0;
            that.selProType = ''
            that.currentLevel = null;
            that.level.map(nn => {
              nn.showNum = false;
              nn.number = 0;
            })
          }
        },2000)
      })
    },
    toAddQI(){
      let that = this;
      let pro = this.listGoods[this.currentGoods], number=0, grade_id='', grade_name='', grade_number='';
      this.level.map(item=>{
        number += item.number*1;
        grade_id += item.id + ',';
        grade_name += item.qlty_grade_name + ',';
        if(item.number != 0){
          grade_number += item.number + ','
        } else {
          grade_number += ','
        }
      })
      let color_name = '';
      if(that.listColor.length>0 && that.listColor[that.currentGoods] && that.listColor[that.currentGoods][that.currentColors]){
        color_name = that.listColor[that.currentGoods][that.currentColors].color_name;
      }
      let trademark='';
      if(this.trademark[this.currentTrademark]){
        trademark= this.trademark[this.currentTrademark].clientFullName;
      }
      if(pro==undefined){

      alert("请选择产品");
      return;
      }

      let productAll = ''
      if(that.selectedSpecification == ''){
          productAll = pro.model
      }
      if(that.selectedSpecification != ''){
          productAll = pro.model +'#'+ that.selectedSpecification
      }   
      
      let newParam = {
        proCode: productAll,//产品型号
        workerCode: this.worker.employee_no,//工号
        workerName: this.worker.name,//
        color: color_name,//颜色，传字符串
        workspace: null,//成型车间
        number: number,//送检总数
        gradeId: grade_id.substring(0, grade_id.length-1),//等级id
        gradeName: grade_name.substring(0, grade_name.length-1),//等级name
        gradeNumber: grade_number.substring(0, grade_number.length-1),//采集的各等级的数量
        trademark:trademark,    //商标
      }
      sessionStorage.setItem('newParam', JSON.stringify(newParam))
      this.linkTo('AddQI')
    }
  },
  watch: {
   
  },
  components: {
    myHead,
    toast,
    msg
  }
};
</script>
<style scoped>
.block {
  padding-bottom: 20px;
}
.block p {
  text-align: left;
  font-weight: bold;
  font-size: 18px;
  padding-bottom: 5px;
}
.trademark{
     display: flex;
    float:left

}
.trademark .btn{
  border: 1px solid #fff;
    border-radius: 8px;
    color: #fff;
    font-size: 16px;
    text-align: center;
    cursor: pointer;
        padding: 0 30px;
    height: 44px;
    line-height: 44px;
}
.goods li {
  float: left;
  height: 60px;
  padding: 0 15px;
  display: flex;
  align-items: center;
  font-size: 20px;
  color: #fff;
  background-color: #409EFF;
}
.goods li:last-of-type p {
  font-weight: bold;
}
.colors,
.level {
  display: flex;
  flex-wrap: wrap;
}
.colors .btn,.level .btn {
  padding: 0 30px;
  height: 44px;
  line-height: 44px;
}
.level .num {
  height: 44px;
  padding: 0;
  border: 1px solid #ccc;
  border-radius: 8px;
}
.level .num span {
  float: left;
  width: 30%;
  text-align: center;
  line-height: 42px;
  font-size: 24px;
  cursor: pointer;
  -moz-user-select:none;
}
.sub{border-right: 1px solid #ccc;}
.add{border-left: 1px solid #ccc;}
.level .num input {
  float: left;
  width: 40%;
  text-align: center;
  line-height: 40px;
  border: none;
  outline: none;
}
.tbText {
  display: inline-block;
  width: 20%;
  font-size: 16px
}
.tb{
  width: 150px;
  height: 60px;
  background: limegreen;
  border-radius: 9px;
  cursor: default;
  font-size: 15px;
  color: #fff;
  line-height: 60px;
}
/* @media screen and (min-width:500px) and (max-width:600px) {
  .footBtn div{
    min-height: 30px;
    padding: 0 10px;
    font-size: 12px;
    border-radius: 5px;
    min-width: 60px;
    margin-left: 5px;
  }
} */
</style>
